site_name: Mes Documentations
#site_url: https://qdemouliere.github.io/cub
#copyright: Licence CC 4.0 FR BY-NC-SA - 2025 D. Balny et Q. Demoulière - Lycée Paul-Louis Courier 

theme:
  name: material
  logo: ./media/web/hdd-network.svg
  favicon: ./media/web/hdd-network.svg
  language: fr
  features:
    - navigation.footer
    - content.code.copy

plugins:
  - search

extra_javascript:
  # MathJax pour le rendu LaTeX
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/mathjax-init.js

markdown_extensions:
  - admonition
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex
