site_name: Mes Documentations
#site_url: https://qdemouliere.github.io/cub
#copyright: Licence CC 4.0 FR BY-NC-SA - 2025 D. Balny et Q. Demoulière - Lycée Paul-Louis Courier
#repo_url: https://github.com/<ton-utilisateur>/<nom-du-repo>
theme:
  name: material
  features:
    - md_in_html
    - navigation.footer
    - content.code.copy
    - navigation.expand
    - navigation.top
    - content.code.annotate
    - content.tabs.link
  language: fr

markdown_extensions:
  # Markdown enrichi
  - tables
  - attr_list
  - def_list
  - footnotes
  # Admonitions et emphase
  - admonition
  - pymdownx.details
  - pymdownx.betterem:
      smart_enable: all
  # Code et coloration
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  # Onglets et organisation
  - pymdownx.tabbed:
      alternate_style: true
  # Mathématiques
  - pymdownx.arithmatex:
      generic: true
  # Table des matières
  - toc:
      permalink: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
